### ISSUE TITLE
Multiple rows and columns

### ISSUE THREAD

**Issue by sateeshblacky** [MobileSolution/android-draggable-viewpager#1]
Actually you have given column count equals to 1, when i change the column count to 4 the view dragger does not work properly as it was wroking for column count 1.
When i long clicking on the particular view the animation will be performing to the previous view.
So could you please let me know the  things to working out in DragDropGrid class .

**Comment by geftimov** [comment]
This library is deprecated , I did not work on it for more than 2 years. Please find better alternatives because they will give you the support you need.

**Comment by sateeshblacky** [comment]
Thank you for the reply. we will see other solution.
Can you suggest me if you have any other alternatives or any other links , if you do not mind.
